quarkus.http.port=8080
quarkus.http.host=0.0.0.0

quarkus.reactive-pg-client.host=${DB_HOST:postgres}
quarkus.reactive-pg-client.port=5432
quarkus.reactive-pg-client.database=bench
quarkus.reactive-pg-client.user=bench
quarkus.reactive-pg-client.password=bench
quarkus.reactive-pg-client.max-size=16
