package gofiber
package main




































































































































































}	log.Fatal(app.Listen(":8080"))	}))		}			}				hub.Broadcast(topic, payload)				payload, _ := json.Marshal(req["payload"])			case "broadcast":				hub.Subscribe(topic, c)			case "subscribe":			switch action {			}				topic = "default"			if topic == "" {			topic, _ := req["topic"].(string)			action, _ := req["action"].(string)			}				continue			if json.Unmarshal(msg, &req) != nil {			var req map[string]interface{}			}				break			if err != nil {			_, msg, err := c.ReadMessage()		for {		}()			c.Close()			hub.Unsubscribe(c)		defer func() {	app.Get("/ws", websocket.New(func(c *websocket.Conn) {	})		return fiber.ErrUpgradeRequired		}			return c.Next()		if websocket.IsWebSocketUpgrade(c) {	app.Use("/ws", func(c *fiber.Ctx) error {	// ── WebSocket ──	})		return c.JSON(out)		}			return c.Status(404).JSON(fiber.Map{"error": "not found"})		if err != nil {		).Scan(&out.ID, &out.Name, &out.Value, &out.CreatedAt)			"SELECT id,name,value,created_at::text FROM items WHERE id=$1", id,		err := pool.QueryRow(ctx,		var out ItemOut		id, _ := strconv.Atoi(c.Params("id"))	app.Get("/items/:id", func(c *fiber.Ctx) error {	})		return c.Status(201).JSON(out)		}			return c.Status(500).JSON(fiber.Map{"error": err.Error()})		if err != nil {		).Scan(&out.ID, &out.Name, &out.Value, &out.CreatedAt)			item.Name, item.Value,			"INSERT INTO items(name,value) VALUES($1,$2) RETURNING id,name,value,created_at::text",		err := pool.QueryRow(ctx,		var out ItemOut		}			return c.Status(400).JSON(fiber.Map{"error": "bad request"})		if err := c.BodyParser(&item); err != nil {		var item ItemIn	app.Post("/items", func(c *fiber.Ctx) error {	// ── CRUD ──	})		ReadBufferSize: 8192,		WriteTimeout:  10 * time.Second,		ReadTimeout:   10 * time.Second,		Prefork:       false,	app := fiber.New(fiber.Config{	hub := NewHub()	}		time.Sleep(time.Second)		}			break		if err := pool.Ping(ctx); err == nil {	for i := 0; i < 30; i++ {	// Wait for DB	defer pool.Close()	}		log.Fatal(err)	if err != nil {	pool, err := pgxpool.New(ctx, dsn)	ctx := context.Background()	dsn := fmt.Sprintf("postgres://bench:bench@%s:5432/bench?sslmode=disable&pool_max_conns=50", dbHost)	}		dbHost = "postgres"	if dbHost == "" {	dbHost := os.Getenv("DB_HOST")func main() {// ── Main ─────────────────────────────────────────────────────────────}	}		_ = c.WriteMessage(websocket.TextMessage, msg)	for c := range h.subs[topic] {	defer h.mu.RUnlock()	h.mu.RLock()func (h *Hub) Broadcast(topic string, msg []byte) {}	}		delete(conns, c)	for _, conns := range h.subs {	defer h.mu.Unlock()	h.mu.Lock()func (h *Hub) Unsubscribe(c *websocket.Conn) {}	h.subs[topic][c] = true	}		h.subs[topic] = make(map[*websocket.Conn]bool)	if h.subs[topic] == nil {	defer h.mu.Unlock()	h.mu.Lock()func (h *Hub) Subscribe(topic string, c *websocket.Conn) {}	return &Hub{subs: make(map[string]map[*websocket.Conn]bool)}func NewHub() *Hub {}	subs  map[string]map[*websocket.Conn]bool	mu    sync.RWMutextype Hub struct {// ── WS Hub ───────────────────────────────────────────────────────────}	CreatedAt string `json:"created_at"`	Value     string `json:"value"`	Name      string `json:"name"`	ID        int    `json:"id"`type ItemOut struct {}	Value string `json:"value"`	Name  string `json:"name"`type ItemIn struct {// ── Models ───────────────────────────────────────────────────────────)	"github.com/jackc/pgx/v5/pgxpool"	"github.com/gofiber/fiber/v2"	"github.com/gofiber/contrib/websocket"	"time"	"sync"	"strconv"	"os"	"log"	"fmt"	"encoding/json"	"context"import (